// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBispvQDZOjDvPzZijWpd9TEoe-6oFd10Y',
    appId: '1:848109693599:web:34c087a391b427484fd0aa',
    messagingSenderId: '848109693599',
    projectId: 'ecommerceapp-190ff',
    authDomain: 'ecommerceapp-190ff.firebaseapp.com',
    storageBucket: 'ecommerceapp-190ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58pMN5sLxJXrt80Q_ZLQtlU4ZOZUC7y8',
    appId: '1:848109693599:android:243aed983aa0a22c4fd0aa',
    messagingSenderId: '848109693599',
    projectId: 'ecommerceapp-190ff',
    storageBucket: 'ecommerceapp-190ff.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFUiEYTQp9Zm1XAGcA5NMwXxXeSpefPc',
    appId: '1:848109693599:ios:d9bb70dd5dd6b5254fd0aa',
    messagingSenderId: '848109693599',
    projectId: 'ecommerceapp-190ff',
    storageBucket: 'ecommerceapp-190ff.appspot.com',
    androidClientId: '848109693599-kmkp0egcv86n1ka2pfondkq1gfh7s5f3.apps.googleusercontent.com',
    iosClientId: '848109693599-aupn1igcfl264spgks3pf18r2s215dsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
